#%RAML 1.0 DataType
    type: object
    properties:
      UserID: 
       type: number
       required: false

      first?: 
       type: string
       required: false
      
      last?:  
       type: string
       required: false

      Department?: 
       type: string
       required: false
       