#%RAML 1.0 NamedExample
userexample1:
  [ {
     "UserID": 101,
      "first": "Meron",
      "last": "Hailu",
      "Department": "IT"
  },
  {
     "UserID": 100,
      "first": "helena",
      "last": "Demeke",
      "Department": "DVT"
  }]